'use client'

import { Providers } from '@/app/providers'
import GridLayout from './UI/Atoms/GridLayout'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <GridLayout>
            {children}
          </GridLayout>
        </Providers>
      </body>
    </html>
  )
}
